### ISSUE TITLE
Ability to redirect output

### ISSUE THREAD

**Issue by d9k** [ocpu/question-deno#3] opened 2022-02-19 13:00 UTC
See #1, to use with pipes.

**Comment by ocpu** [comment] 2022-02-19 13:18
Duplicate of #1 and fixed by #2

**Comment by d9k** [comment] 2022-02-19 13:52
@ocpu, thanks for PR accept!

This issue isn't a duplicate, because #1 is about input, and this issue is about output.

I tried to fix by adding `Config.writer` property at `util.ts`:

```
export async function println(text: string, writer?: Deno.Writer) {
  writer = writer || config.writer;
  return writer.write(encoder.encode(text + '\n'))
}
```

used in my app as

```
        questionConfig.keypressReader = tty;
        questionConfig.writer = tty;
```

and got an error

```
 error: Uncaught (in promise) Busy: Resource is unavailable because it is in use by a promise
    if (!Deno.isatty(reader.rid)) {
              ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at Object.isatty (deno:runtime/js/40_tty.js:12:17)
    at readKeypress (https://deno.land/x/keypress@0.0.7/mod.ts:398:15)
    at readKeypress.next (<anonymous>)
    at createRenderer (file:///home/d9k/cr/cli-select/modified/question-deno/util.ts:76:25)
```

**Comment by ocpu** [comment] 2022-02-19 14:42
I have identified the source of the issue and can push an update within the next few minutes addressing it. I can also add the config option as you define it here.

**Closed as completed** 2022-02-19 15:52 UTC

**Comment by d9k** [comment] 2022-02-19 17:38
@ocpu, I'm impressed! :astonished: 

> I have identified the source of the issue

oh, I see, 6bed34dff6e5997501731942e0dcf3941e95c63d :+1: 

About [Function for basic configuration of unix piping (5c88e765a48)](https://github.com/ocpu/question-deno/commit/5c88e765a48cd0aa6a46bf38f4deee4022f47bb3): 
very cool, but shouldn't we close tty `Deno.close(tty.rid)` before the app shutdown?
